import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Index: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    router.push("/restaurant/menu");
  });
  return (
    <>
      <Head>
        <title>todo_app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
    </>
  );
};

export default Index;
